# app/agents/pdf.py

import matplotlib
matplotlib.use("Agg")

import matplotlib.pyplot as plt
from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse
from pydantic import BaseModel
from typing import Optional, Dict, Any
import os
import tempfile
import logging
import json
from datetime import datetime

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Image,
    PageBreak
)
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch

from app.db import SessionLocal
from app.models.chat import ChatHistory

logger = logging.getLogger("pdf")
router = APIRouter()


# =========================
# REQUEST MODEL
# =========================
class PDFRequest(BaseModel):
    conversation_id: str


# =========================
# SAFE PLOTS
# =========================
def safe_plot_market(viz: dict, out_path: str) -> bool:
    market = viz.get("market")
    if not market or not market.get("timeline"):
        return False

    years = [p["year"] for p in market["timeline"]]
    values = [p["value"] for p in market["timeline"]]

    if len(years) < 2:
        return False

    plt.figure(figsize=(7, 4))
    plt.plot(years, values, marker="o", linewidth=3)
    plt.title("Market Growth Forecast")
    plt.ylabel("USD Billion")
    plt.grid(alpha=0.3)
    plt.tight_layout()
    plt.savefig(out_path, dpi=200)
    plt.close()
    return True


def safe_plot_clinical(viz: dict, out_path: str) -> bool:
    clinical = viz.get("clinical")
    if not clinical or clinical.get("total_trials", 0) == 0:
        return False

    labels = []
    sizes = []
    for phase, count in clinical["by_phase"].items():
        if count > 0:
            labels.append(phase.replace("PHASE", "Phase "))
            sizes.append(count)

    if not sizes:
        return False

    plt.figure(figsize=(6, 6))
    plt.pie(sizes, labels=labels, autopct="%1.1f%%", startangle=90)
    plt.title("Clinical Trial Phase Distribution")
    plt.axis("equal")
    plt.tight_layout()
    plt.savefig(out_path, dpi=200)
    plt.close()
    return True


# =========================
# PDF ENDPOINT (DB-DRIVEN)
# =========================
@router.post("/pdf")
async def generate_pdf(req: PDFRequest):
    db = SessionLocal()
    try:
        rows = (
            db.query(ChatHistory)
            .filter(ChatHistory.conversation_id == req.conversation_id)
            .order_by(ChatHistory.id.asc())
            .all()
        )
    finally:
        db.close()

    if not rows:
        raise HTTPException(status_code=404, detail="No conversation history found")

    tmp_dir = tempfile.mkdtemp()
    pdf_path = os.path.join(tmp_dir, "NovusAI_Report.pdf")

    doc = SimpleDocTemplate(
        pdf_path,
        pagesize=A4,
        topMargin=0.8 * inch,
        bottomMargin=0.8 * inch
    )

    styles = getSampleStyleSheet()
    story = []

    story.append(Paragraph("NovusAI Drug Repurposing Intelligence Report", styles["Title"]))
    story.append(Paragraph(
        f"Generated on {datetime.now().strftime('%B %d, %Y at %H:%M')}",
        styles["Normal"]
    ))
    story.append(Spacer(1, 20))

    for idx, row in enumerate(rows, start=1):
        story.append(Paragraph(f"<b>Query {idx}</b>", styles["Heading3"]))
        story.append(Spacer(1, 6))
        story.append(Paragraph(row.question, styles["Normal"]))
        story.append(Spacer(1, 10))

        for para in row.answer.split("\n\n"):
            if para.strip():
                story.append(Paragraph(para.replace("\n", "<br/>"), styles["Normal"]))
                story.append(Spacer(1, 8))

        if row.visualizations_json:
            viz = json.loads(row.visualizations_json)

            market_path = os.path.join(tmp_dir, f"market_{idx}.png")
            clinical_path = os.path.join(tmp_dir, f"clinical_{idx}.png")

            if safe_plot_market(viz, market_path):
                story.append(Spacer(1, 12))
                story.append(Paragraph("Market Growth Forecast", styles["Heading2"]))
                story.append(Image(market_path, width=6.5 * inch, height=4 * inch))

            if safe_plot_clinical(viz, clinical_path):
                story.append(Spacer(1, 12))
                story.append(Paragraph("Clinical Trial Phase Distribution", styles["Heading2"]))
                story.append(Image(clinical_path, width=5 * inch, height=5 * inch))

        story.append(PageBreak())

    story.append(Paragraph(
        "Generated by NovusAI — AI-powered drug repurposing platform",
        styles["Italic"]
    ))

    doc.build(story)

    return FileResponse(
        pdf_path,
        media_type="application/pdf",
        filename=f"NovusAI_{req.conversation_id}.pdf",
    )
